

adaface:
  zero:
    # 预训练模型
    model: ir_101
    # 预训练模型名字
    model_file: pretrained/adaface_ir101_webface12m.ckpt



queue:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 1 
  single_face_queue_key: "A_205_Face"
  single_adaface_queue_key: "A_205_Adaface"
  # 队列阻塞时间，超过这个是按
  timeout: 300    

